version: "3"
services:

  pihole:
    restart: always
    container_name: pihole
    image: diginc/pi-hole:arm
    volumes:
      - pihole_data:/etc/pihole
      - dnsmasq_data:/etc/dnsmasq.d
    environment:
      - ServerIP=${SERVER_IP}
      - DNS1=${UPSTREAM_DNS1}
      - DNS2=${UPSTREAM_DNS2}
    cap_add:
      - NET_ADMIN
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80"

volumes:
  pihole_data:
  dnsmasq_data: